### ISSUE TITLE
Tengine closing connection with GOAWAY if client sends SETTINGS_MAX_HEADER_LIST_SIZE with too large value in initial SETTINGS frame

### ISSUE THREAD

**Issue by jrhames** [alibaba/tengine#930] opened 2017-08-30 17:26 UTC
Experienced between Chrome 62.0.3167.0 and above and ​https://www.mercadolivre.com.br (as well as https://www.mercadolibre.com.ar), which runs Tengine according to the response headers but I am not able to determine the version. 

oblivia:~ francisco$ curl -I https://www.mercadolibre.com.ar/
HTTP/1.1 200 OK
Server: Tengine

If the client does not send a SETTINGS_MAX_HEADER_LIST_SIZE field in the initial settings frame, or sends one with value less than or equal to 32768, then the request succeeds.
If the client sends a SETTINGS_MAX_HEADER_LIST_SIZE value greater than 32768, then Tengine responds with a GOAWAY frame with last_accepted_stream_id = 0, error_code = NO_ERROR, and no debug data.

This, however, does not make sense: the client sending a SETTINGS_MAX_HEADER_LIST_SIZE value tells the server how long response headers the client is willing to accept at maximum. Larger value means the client is willing to accept larger responses. It does not ask or require the server to use more memory.

See ​https://crbug.com/751642 for Chrome bug.

**Comment by yaoweibin** [comment] 2017-09-01 02:17
@chobits Could you check this? seems a SPDY BUG.

**Comment by chobits** [comment] 2017-09-01 08:24
hi @yaoweibin @jrhames 
yes, I am trying to reproduce in Tengine

**Comment by bullerdu** [comment] 2017-09-01 08:39
@jrhames i write a go http2-client to reproduce the issue in Tengine, but not reproduce. the code as follows:
```
package main

import (
	"crypto/tls"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"

	"golang.org/x/net/http2"
)

func main() {
	hc := &http.Client{
		Transport: &http2.Transport{
			TLSClientConfig: &tls.Config{
				InsecureSkipVerify: true,
			},
			MaxHeaderListSize: 65536,
		},
	}

	resp, err := hc.Get("https://localhost:11443/hello")
	if err != nil {
		log.Fatal(err)
	}

	body, _ := ioutil.ReadAll(resp.Body)
	resp.Body.Close()
	fmt.Printf("%s", body)

}
```

**Comment by chobits** [comment] 2017-09-01 14:57
hi , from nginx ticket &  ​https://crbug.com/751642 , we think this is not nginx/tengine bug. 
nginx/tengine will ignore SETTINGS_MAX_HEADER_LIST_SIZE.

See vbart's comment in https://trac.nginx.org/nginx/ticket/1351:

> It doesn't make any sense, because nginx doesn't process SETTINGS_MAX_HEADER_LIST_SIZE value at all. The value just ignored by nginx since the initial commit of HTTP/2 implementation.
We've tested with all currently supported versions of nginx and can't reproduce.
I guess, something else is involved there: 3-rd party patches, or some proxy in front of nginx.

**Comment by chobits** [comment] 2017-09-05 05:39
Think it a wont fix. I'am closing this issue. 
Feel free to reopen this if you are still seeing this issue.

**Closed by chobits** 2017-09-05 05:39 UTC

**Comment by jrhames** [comment] 2017-09-05 17:20
The only odd thing, is that on the websites I listed, I'm still receiving a GOAWAY. Any clues them on what might be going on? Since I can't verify the Tengine version running on those servers, do you think it may be an outdated version misbehaving?

**Comment by chobits** [comment] 2017-09-06 06:42
hi @jrhames 

Tenigne/nginx will not handle SETTINGS_MAX_HEADER_LIST_SIZE, so it will receive this SETTING frame and do nothing for SETTINGS_MAX_HEADER_LIST_SIZE parameter. 

(If your client receives GOAWAY in this case. I think it's some other proxy in front of nginx, see [this comment](https://bugs.chromium.org/p/chromium/issues/detail?id=751642#c13) for one possibility.)

> The only odd thing, is that on the websites I listed, I'm still receiving a GOAWAY.

If you mean GOAWAY after all handled requests, this is normal. Tenigne/nginx will send GOAWAY before closing http2 connection.

**Comment by jrhames** [comment] 2017-09-06 15:50
Thanks for the update, @chobits
