### ISSUE TITLE
[req_status_zone] $upstream_addr is returned blank for POST request 

### ISSUE THREAD

**Issue by XavM** [alibaba/tengine#614] opened 2015-05-26 16:34 UTC
When using **$upstream_addr** as part of the key used in req_status_zone, its value is returned blank for **POST** requests, when returned from the "req_status_show" location 

(The value of $upstream_addr is properly set for GET requests)

**Conf Ex :** 

	http {
		req_status_zone stats  "$request_method,$upstream_addr" 10M;
		req_status stats;

		upstream nodes  {
			server node1:8080 weight=10;
			server node2:8080 weight=10;
		}

		server {
			listen 80;

			location / {
				proxy_pass  http://nodes;
			}

			location /stats {
				req_status_show stats;
			}
		}
	}

**Requests Ex :** 

	$>curl -X POST 127.0.0.1/fakePOST
	$>curl -X POST 127.0.0.1/fakePOST
	$>curl -X GET 127.0.0.1/fakeGET 
	$>curl -X GET 127.0.0.1/fakeGET 
	$>curl 127.0.0.1/stats
		POST,,1036,724,4,4,4,0,0,0,0,6,4,6,5
		GET,192.168.0.228:8080,20624,5456,24,24,4,0,20,0,0,38,24,38,24
		GET,192.168.0.152:8080,996,237,1,1,0,0,1,0,0,2,1,2,2

**Comment by tanguofu** [comment] 2015-06-16 12:09
what is your tengine version? 
i had test Tengine version: Tengine/2.1.0 (nginx/1.6.2), it works well.

**Comment by XavM** [comment] 2015-06-17 14:13
Hello @tanguofu,

We have the problem with 2.0.3 and 2.1.0

I just did some test with a fresh new 2.1.0 compiled from source, and the problem is still present 

**OS :** Linux CentOS 6.5 X86_64 minimal install

**Compile steps :** 

	yum install pcre-devel.x86_64 openssl.x86_64 openssl-devel.x86_64 zlib-devel.x86_64 gcc.x86_64 -y
	mkdir -p /tmp/sources
	cd /tmp/sources
	wget https://github.com/alibaba/tengine/archive/tengine-2.1.0.tar.gz 
	tar zxvf ./tengine-2.1.0.tar.gz
	cd /tmp/sources/tengine-tengine-2.1.0

	./configure \
		--prefix=/opt/tmp-nginx-0.2.0 \
		--pid-path=/var/run/nginx.pid \
		--http-log-path=/var/log/nginx/access.log \
		--error-log-path=/var/log/nginx/error.log \
		--with-http_ssl_module \
		--with-http_stub_status_module \
		--without-http_fastcgi_module \
		--without-http_uwsgi_module \
		--without-http_scgi_module \
		--without-dso 

	make

	mkdir -p /tmp/installdir
	make install DESTDIR=/tmp/installdir

**Conf file :**

	worker_processes  1;

	events {
			worker_connections  1024;
	}

	http {
			req_status_zone stats  "$request_method,$upstream_addr" 10M;
			req_status stats;

			upstream nodes  {
					server node1:8080 weight=10;
					server node2:8080 weight=10;
			}

			server {
					listen 80;

					location / {
							proxy_pass  http://nodes;
					}

					location /stats {
							req_status_show stats;
					}
			}
	}  

**GET and POST example :**

	$>curl -X POST 127.0.0.1/fakePOST
	$>curl -X POST 127.0.0.1/fakePOST
	$>curl -X GET 127.0.0.1/fakeGET 
	$>curl -X GET 127.0.0.1/fakeGET 
	$>curl 127.0.0.1/stats

	GET,,808,407,1,2,2,0,0,0,0,0,0,0,0
	POST,,1300,332,2,2,2,0,0,0,0,107,2,107,2

**Comment by tanguofu** [comment] 2015-06-22 09:30
er, can  node1 and node1 be resolved in your test server？  could your try with real ip of node1 or node2 ？

**Comment by XavM** [comment] 2015-06-23 13:58
Hi @tanguofu,

Yes, node1 and node2 can be resolved from within the nginx test server 
Just to make sure, i have replaced the 2 hostnames with their corresponding IPs, but the problem is the same

As I was mentioning in the first post of this issue, the value of the $upstream_addr is properly reported for GET requests, and is kept blank for POST requests only

Did you test with **POST** requests ?

Regards

**Comment by chobits** [comment] 2015-08-13 12:33
@XavM
Could you log $upstream_addr in access log, and show us your access log.

**Comment by XavM** [comment] 2015-08-25 14:57
Yes sure : 

Fresh logs and stats :

    service nginx restart \
    && echo "" >  /var/log/nginx/access.log \
    && curl 127.0.0.1 -d - \
    && curl 127.0.0.1 -d - \
    && curl 127.0.0.1/stats \
    && cat /var/log/nginx/access.log

Output of the previous commands : 

>
    Stopping nginx:                                            [  OK  ]
    Starting nginx:                                            [  OK  ]
    POST -> ct2
    POST -> ct3
    POST,,470,468,2,2,2,0,0,0,0,5,2,5,2
    192.168.0.23:8080 "POST / HTTP/1.1" 200 200
    192.168.0.69:8080 "POST / HTTP/1.1" 200 200
    - "GET /stats HTTP/1.1" 200 -
>

Corresponding Tengine configuration : 

    cat /opt/nginx/conf/nginx.conf

>
    worker_processes  1;
    events {
            worker_connections  1024;
    }
    http {
            log_format  main  '$upstream_addr "$request" $status $upstream_status';
            access_log logs/access.log main;
            req_status_zone stats  "$request_method,$upstream_addr" 10M;
            req_status stats;
            upstream nodes  {
                    server ct2:8080 weight=10;
                    server ct3:8080 weight=10;
            }
            server {
                    listen 80;
                    location / {
                        proxy_pass  http://nodes;
                    }
                    location /stats {
                            req_status_show stats;
                    }
            }
    }
>

The basic app running on ct2:8080 and ct3:8080 is responding with "HTTP_VERB -> hostname"
Here is the code : 

    node -v && cat ./http.js 

>
```
v0.12.2
#!/usr/bin/node
var os = require('os');
var express = require('express');
var app = express();
app.get('/', function (req, res) {
  res.send('GET -> ' + os.hostname() + '\n');
});
app.post('/', function (req, res) {
  res.send('POST -> ' + os.hostname() + '\n');
});
var server = app.listen(8080, function () {
  var host = server.address().address;
  var port = server.address().port;
  console.log('Listening at http://%s:%s', host, port);
});
```
>

Let me know if you have any more questions or debug needs that could help resolve the issue
I would be glad to help

**Comment by cfsego** [comment] 2015-08-27 03:29
$upstream_addr is pending until logging. something is wrong when using this variable as part of key.
there will be a simple patch for this very soon, fit for case that requests and responses are short.

**Comment by chobits** [comment] 2015-08-27 03:32
@XavM 
I have reproduced this problem.
For the POST request, reqstat module calculates zone key "$request_method,$upstream_addr" in input body filter before upstream phase. In such case, the zone key is empty string and all the status information of this request will be stored in to this key slot.

**Comment by nanfenglei22** [comment] 2015-08-28 01:57
i have modified this bug url:https://github.com/nanfenglei22/tengine/commit/d7411f10251dbd7378a20d882d2fd730c0fdabe7

**Comment by cfsego** [comment] 2015-11-26 09:04
For now, I still do not support variables connected with response. Because I will lose dynamic status of bytein and byteout. But you can patch it as you will.
maybe I will add  a directive 'reqstat_dynamic' to control it in future, but now, I haven't make up my mind.

**Closed by cfsego** 2015-11-26 09:04 UTC
Labels: bug
